#!/bin/bash
echo "These are the disks currently on your pc:"
fdisk -l

read -p "Which disk do you wish to use?:" diskdev

fdisk $diskdev

echo "Your drives are now partitioned as follows:"
fdisk -l

read -p "What is your system partition?: " syspart
read -p "What is your boot partition?: " bootpart
read -p "What is your SWAP partition?: " swappart

# Format partitions
mkfs.ext4 $syspart
mkswap $swappart
mkfs.fat -F 32 $bootpart

# Mount
mount $syspart /mnt
mount --mkdir $bootpart /mnt/boot
swapon $swappart

# Setup mirrors
pacman -Sy python3 reflector

echo "Refreshing mirrors (This might take a while)"
reflector --latest 100 --sort rate --save /etc/pacman.d/mirrorlist

# Install (Essential) packages
pacstrap -K /mnt base linux linux-firmware grub efibootmgr

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB

clear
echo "Base system should be installed now. \nVisiting the post-chroot segment of the arch wiki's installation guide is highly recommended. \nYou can find it at: https://wiki.archlinux.org/title/Installation_guide#Time \nKeep in mind, while user accounts and such have not been made yet, a bootloader (grub) has already been installed by the installer. \nGoing into Chroot now."
arch-chroot /mnt